import streamlit
streamlit.header('tarun')
streamlit.title('my parents new healthy diner')
streamlit.title('my parents new healthy diner')
streamlit.text('breakfast menu')
streamlit.text('omega 3 bluberry oatmeal')
streamlit.text('Kale, Spinach & Rocket Smoothie')
streamlit.text('Hard-Boiled Free-Range Egg')
streamlit.header('Breakfast favorites')
streamlit.text('breakfast menu')
streamlit.text(' 🥣 omega 3 bluberry oatmeal')
streamlit.text(' 🥗 Kale, Spinach & Rocket Smoothie')
streamlit.text(' 🐔 Hard-Boiled Free-Range Egg')
streamlit.text(' 🥑🍞 Avocado Toast')

